# Generated by Django 4.2.10 on 2024-09-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest_round1',
            name='ans',
            field=models.CharField(default='', max_length=250),
        ),
    ]
