# Generated by Django 4.2.10 on 2024-09-21 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_quest_round1_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest_round1',
            name='team',
        ),
    ]
