# Generated by Django 4.2.10 on 2024-09-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_quest_round1_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest_round1',
            name='pass_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='quest_round1',
            name='qes_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quest_round1',
            name='score',
            field=models.IntegerField(default=10),
        ),
    ]
