# Generated by Django 5.1 on 2024-09-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_options_quest_round2_options_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='question',
        ),
    ]
