# Generated by Django 5.1 on 2024-09-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_options_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest_round2',
            name='correct_answer',
        ),
        migrations.RenameField(
            model_name='quest_round2',
            old_name='question',
            new_name='quest',
        ),
        migrations.AddField(
            model_name='quest_round2',
            name='ans',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest_round2',
            name='deduct',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='quest_round2',
            name='option1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest_round2',
            name='option2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest_round2',
            name='option3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest_round2',
            name='option4',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest_round2',
            name='score',
            field=models.IntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
