# Generated by Django 5.1 on 2024-09-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_quest_round2_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest_round2',
            name='ans',
            field=models.IntegerField(default=10),
        ),
    ]
