# Generated by Django 5.1 on 2024-09-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_quest_round2_qes_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round1_rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=250)),
                ('rules', models.JSONField(default=list)),
            ],
        ),
    ]
