# Generated by Django 5.1 on 2024-09-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_team_spec'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Round1_rules',
            new_name='Rounds',
        ),
    ]
