# Generated by Django 5.1 on 2024-09-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_rename_round1_rules_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='round',
            field=models.CharField(default='', max_length=250),
        ),
    ]
