# Generated by Django 5.1 on 2024-10-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_quest_round2_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest_round2',
            name='ans',
            field=models.IntegerField(default=1),
        ),
    ]
