# Generated by Django 5.1 on 2024-10-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_quest_round2_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest_round3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qes_id', models.IntegerField(default=0)),
                ('quest', models.CharField(max_length=255)),
                ('ans', models.IntegerField(default=1)),
                ('option1', models.CharField(default='', max_length=100)),
                ('option2', models.CharField(default='', max_length=100)),
                ('option3', models.CharField(default='', max_length=100)),
                ('option4', models.CharField(default='', max_length=100)),
                ('score', models.IntegerField(default=50)),
                ('deduct', models.IntegerField(default=20)),
            ],
        ),
    ]
