# Generated by Django 5.1 on 2024-10-05 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_quest_round3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dugout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.team')),
            ],
        ),
    ]
