# Generated by Django 5.1 on 2024-10-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_dugout'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
