# Generated by Django 5.1 on 2024-10-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_rounds_timer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Tea_m',
        ),
    ]
