# Generated by Django 5.1 on 2024-10-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_rename_team_tea_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea_m',
            name='t_id',
            field=models.IntegerField(default=0),
        ),
    ]
