# Generated by Django 5.1 on 2024-10-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_tea_m_t_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest_round4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qes_id', models.IntegerField(default=0)),
                ('quest', models.CharField(max_length=255)),
                ('ans', models.CharField(default='', max_length=100)),
                ('score', models.IntegerField(default=50)),
                ('deduct', models.IntegerField(default=20)),
            ],
        ),
    ]
