# Generated by Django 5.1 on 2024-10-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_quest_round4'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest_round4',
            name='media_url',
            field=models.URLField(default=''),
        ),
    ]
