# Generated by Django 4.2.10 on 2024-10-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_quest_round4_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea_m',
            name='dug_out',
            field=models.BooleanField(default=False),
        ),
    ]
